language: android
jdk:
  - oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.0
  - android-23
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew build check --daemon"
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
